name: Build Manifest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: 'Update manifest'
          author_name: GitHub Actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
